### ISSUE TITLE
--preset=next doesn't support dynamic routing?

### ISSUE THREAD

**Issue by tkc310** [fastly/compute-js-static-publish#2]
Below is an issue of next.js.
https://github.com/vercel/next.js/discussions/32375

If we run `publish` with the following directory structure,
direct access to the URL `/posts/uuid-1` will result in a 404.

https://github.com/tkc310/fastly_next/tree/3e466a3e4225e56c7740d47032070038ea000534/pages/posts

```
- pages/posts/
  - index.js
  - [id].js
```

`./compute-js/index.js` by modifying it as follows, but is there a better solution?
(This solution would require maintenance every time more routing is added)

https://github.com/tkc310/fastly_next/commit/f2894a17e014ce29656e86d1456ed54c22930eaa

**Comment by harmony7** [comment]
Correct, this next dynamic routing is not supported by this tool. `compute-js-static-publish` only handles the output from `next export`, which expects to have its output uploaded directly to a traditional web server.

It's exactly the same thing as discussed in https://github.com/vercel/next.js/discussions/32375. The `[id]` is a next-ism that is outside the scope of this tool.

Next.js's [page on `next export`](https://nextjs.org/docs/advanced-features/static-html-export) includes `Dynamic Routes when using getStaticPaths` as a supported feature. If your potential `[id]` values are not known ahead of time, you cannot use dynamic routes with `next export`.

Depending on your needs, instead of using `next export` + `compute-js-static-publish`, consider using [next-compute-js](https://github.com/fastly/next-compute-js), which runs your next application in Compute@Edge.

Closing this, as this is outside the scope of this tool. Feel free to reopen if you have any other comments.

**Comment by tkc310** [comment]
Thank you for your response.
Sorry for the delay in confirming this, but I understand the expected behavior in the relevant configuration.
